### ISSUE TITLE
unable to use _text in params as defined in README

### ISSUE THREAD

**Issue by pivotal-jesse-alvarez** [mdomke/concourse-email-resource#3]
using default configuration: 

```
  - put: send-email
    params:
      to: [user@domain.com]
      subject_text: Job info
      body_text: this is the body
```

Error:

```
Using dir /tmp/build/put
Logging payload to /tmp/tmpzek9pz52
Unable to extract 'subject' from 'params'

unexpected end of JSON input
```
