### ISSUE TITLE
subject text not picking up variables.

### ISSUE THREAD

**Issue by mrmcmuffinz** [mdomke/concourse-email-resource#6]
**Scenario**

Trying to send email after task completion for `on_success` and `on_failure` but the `subject_text` is not being constructed properly.

**Code**

```       
- put: send-email
    params:
      to_file: email-message/to_file.txt
      subject_text: Concourse CI $BUILD_PIPELINE_NAME Failure
      body: slack-message/slack.message.txt
```

Even if I encapsulate the `subject_text` with double quotes to represent it as a string the variables are still not being evaluated. Any idea why this is the case?
